### ISSUE TITLE
mepserver and mepauth containers exiting after start-up

### ISSUE THREAD

**Issue by bastien-internship** [EdgeGallery/mep#3]
After successfully deploying postgres container, running kong migration and deploying kong service container, both mepauth and mepserver containers exit and an error related to "Elasticsearch node" is raised.
I followed this repository readme and the documentation at [gitee repository](https://gitee.com/edgegallery/docs/blob/master/Projects/MEP/EdgeGallery%E6%9C%AC%E5%9C%B0%E5%BC%80%E5%8F%91%E9%AA%8C%E8%AF%81%E6%9C%8D%E5%8A%A1%E8%AF%B4%E6%98%8E%E4%B9%A6.md#EG-LDVS-MEP%E9%83%A8%E7%BD%B2%E6%8C%87%E5%AF%BC).

Could you provide some insight on the origin of these failures ?

Thanks in advance for any help or advice.

Logs : 

> 2021-11-08T08:42:35.626Z	INFO	backend/discovery.go:150	install new type 0:SERVICE->/cse-sr/ms/files/
> 2021-11-08T08:42:35.631Z	INFO	backend/discovery.go:150	install new type 1:INSTANCE->/cse-sr/inst/files/
> 2021-11-08T08:42:35.631Z	INFO	backend/discovery.go:150	install new type 2:DOMAIN->/cse-sr/domains/
> 2021-11-08T08:42:35.631Z	INFO	backend/discovery.go:150	install new type 3:SCHEMA->/cse-sr/ms/schemas/
> 2021-11-08T08:42:35.631Z	INFO	backend/discovery.go:150	install new type 4:SCHEMA_SUMMARY->/cse-sr/ms/schema-sum/
> 2021-11-08T08:42:35.631Z	INFO	backend/discovery.go:150	install new type 5:RULE->/cse-sr/ms/rules/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 6:LEASE->/cse-sr/inst/leases/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 7:SERVICE_INDEX->/cse-sr/ms/indexes/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 8:SERVICE_ALIAS->/cse-sr/ms/alias/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 9:SERVICE_TAG->/cse-sr/ms/tags/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 10:RULE_INDEX->/cse-sr/ms/rule-indexes/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 11:DEPENDENCY_RULE->/cse-sr/ms/dep-rules/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 12:DEPENDENCY_QUEUE->/cse-sr/ms/dep-queue/
> 2021-11-08T08:42:35.632Z	INFO	backend/discovery.go:150	install new type 13:PROJECT->/cse-sr/projects/
> 2021-11-08T08:42:35.643Z	INFO	plugin/plugin.go:67	load 'cipher' plugin named 'mepserver_tls'
> 2021-11-08T08:42:35.645Z	INFO	rest/route.go:107	register servant controller/v4.MainService
> 2021-11-08T08:42:35.646Z	INFO	rest/route.go:133	register route /v4/:project/registry/version(GET)
> 2021-11-08T08:42:35.646Z	INFO	rest/route.go:133	register route /v4/:project/registry/health(GET)
> 2021-11-08T08:42:35.646Z	INFO	rest/route.go:107	register servant controller/v4.MicroServiceService
> 2021-11-08T08:42:35.646Z	INFO	rest/route.go:133	register route /v4/:project/registry/existence(GET)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices(GET)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId(GET)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices(POST)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/properties(PUT)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId(DELETE)
> 2021-11-08T08:42:35.647Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices(DELETE)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:107	register servant controller/v4.SchemaService
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/schemas/:schemaId(GET)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/schemas/:schemaId(PUT)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/schemas/:schemaId(DELETE)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/schemas(POST)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/schemas(GET)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:107	register servant controller/v4.DependencyService
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/dependencies(POST)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/dependencies(PUT)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:consumerId/providers(GET)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:providerId/consumers(GET)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:107	register servant controller/v4.TagService
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/tags(POST)
> 2021-11-08T08:42:35.648Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/tags/:key(PUT)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/tags(GET)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/tags/:key(DELETE)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:107	register servant controller/v4.RuleService
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/rules(POST)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/rules(GET)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/rules/:rule_id(PUT)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/rules/:rule_id(DELETE)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:107	register servant controller/v4.MicroServiceInstanceService
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/instances(GET)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/instances/action(POST)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances(GET)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances/:instanceId(GET)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances(POST)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances/:instanceId(DELETE)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances/:instanceId/properties(PUT)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances/:instanceId/status(PUT)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/instances/:instanceId/heartbeat(PUT)
> 2021-11-08T08:42:35.649Z	INFO	rest/route.go:133	register route /v4/:project/registry/heartbeats(PUT)
> 2021-11-08T08:42:35.650Z	INFO	rest/route.go:107	register servant controller/v4.WatchService
> 2021-11-08T08:42:35.650Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/watcher(GET)
> 2021-11-08T08:42:35.650Z	INFO	rest/route.go:133	register route /v4/:project/registry/microservices/:serviceId/listwatcher(GET)
> 2021-11-08T08:42:35.653Z	INFO	dns/rest.go:65	New DNS agent initialization.
> 2021-11-08T08:42:35.653Z	INFO	mp1/controller.go:97	Data plane initialized to none.
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:107	register servant mepserver/mp1.Mp1Service
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/subscriptions(POST)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/subscriptions(GET)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/subscriptions/:subscriptionId(GET)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/subscriptions/:subscriptionId(DELETE)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services(POST)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services(GET)
> 2021-11-08T08:42:35.654Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services/:serviceId(PUT)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services/:serviceId(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services/:serviceId(DELETE)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/subscriptions(POST)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/subscriptions(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/subscriptions/:subscriptionId(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/subscriptions/:subscriptionId(DELETE)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/dns_rules(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/dns_rules/:dnsRuleId(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/dns_rules/:dnsRuleId(PUT)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services/:serviceId/liveness(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/applications/:appInstanceId/services/:serviceId/liveness(PUT)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /health(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/services(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/services/:serviceId(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/traffic_rules(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/traffic_rules/:trafficRuleId(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/traffic_rules/:trafficRuleId(PUT)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/timing/current_time(GET)
> 2021-11-08T08:42:35.655Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/timing/timing_caps(GET)
> 2021-11-08T08:42:35.656Z	INFO	rest/route.go:133	register route /mep/mec_service_mgmt/v1/transports(GET)
> 2021-11-08T08:42:35.656Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/confirm_ready(POST)
> 2021-11-08T08:42:35.656Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/confirm_termination(POST)
> 2021-11-08T08:42:35.660Z	INFO	plugin/plugin.go:67	load 'quota' plugin named 'buildin'
> 2021-11-08T08:42:35.660Z	INFO	discovery/event_proxy.go:71	register event handler[SERVICE_INDEX] quota/counter.ServiceIndexEventHandler
> 2021-11-08T08:42:35.660Z	INFO	discovery/event_proxy.go:71	register event handler[INSTANCE] quota/counter.InstanceEventHandler
> 2021-11-08T08:42:35.663Z	ERROR	util/requestutil.go:63	Validate server name error.
> 2021-11-08T08:42:35.663Z	INFO	plugin/plugin.go:67	load 'quota' plugin named 'buildin'
> 2021-11-08T08:42:35.663Z	INFO	discovery/event_proxy.go:71	register event handler[INSTANCE] mp1/event.InstanceEtsiEventHandler
> 2021-11-08T08:42:35.667Z	INFO	plans/kong_http_log.go:70	Create es client.
> 
> 2021-11-08T08:42:40.681Z	ERROR	plans/kong_http_log.go:73	Connect to es fail.	{"error": "health check timeout: Head \"http://mep-elasticsearch:9200\": proxyconnect tcp: dial tcp: lookup xxx.xxx.xx: device or resource busy: no Elasticsearch node available"}
> 2021-11-08T08:42:40.682Z	INFO	dns/rest.go:65	New DNS agent initialization.
> 2021-11-08T08:42:40.682Z	INFO	mm5/controller.go:82	Data-plane initialized to none.
> 2021-11-08T08:42:40.682Z	ERROR	util/meputil.go:794	Invalid mep-auth port.
> 2021-11-08T08:42:40.682Z	ERROR	mm5/controller.go:46	Mm5 interface initialization failed.	{"error": "port validation error"}
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:107	register servant mepserver/mm5.Mm5Service
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/app_lcm/v1/applications/:appInstanceId/appd_configuration(POST)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/app_lcm/v1/applications/:appInstanceId/appd_configuration(PUT)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/app_lcm/v1/applications/:appInstanceId/appd_configuration(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/app_lcm/v1/applications/:appInstanceId/appd_configuration(DELETE)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/app_lcm/v1/tasks/:taskId/appd_configuration(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/mec_platform_config/v1/capabilities(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mepcfg/mec_platform_config/v1/capabilities/:capabilityId(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mep/mec_app_support/v1/applications/:appInstanceId/AppInstanceTermination(DELETE)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mep/service_govern/v1/kong_log(POST)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mep/service_govern/v1/kong_log(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mep/service_govern/v1/subscribe_statistic(GET)
> 2021-11-08T08:42:40.683Z	INFO	rest/route.go:133	register route /mep/service_govern/v1/services(GET)
> 2021-11-08T08:42:40.683Z	INFO	plugin/plugin.go:67	load 'uuid' plugin named 'buildin'
> 2021-11-08T08:42:40.683Z	INFO	plugin/plugin.go:67	load 'uuid' plugin named 'mp1context'
> 2021-11-08T08:42:40.685Z	INFO	rest/server_mux.go:57	register serve mux 'default' http handler github.com/apache/servicecomb-service-center/server/rest/ServerHandler, pattern /
> 2021-11-08T08:42:40.689Z	INFO	rest/server_mux.go:57	register serve mux 'default' http handler net/http/HandlerFunc, pattern /metrics
> 2021-11-08T08:42:40.689Z	INFO	metric/reporter.go:35	register metrics reporter 'rest'
> 2021-11-08T08:42:40.691Z	ERROR	registry/config.go:107	auto_sync_interval is invalid	{"error": "time: invalid duration "}
> 2021-11-08T08:42:40.697Z	INFO	discovery/event_proxy.go:71	register event handler[DOMAIN] service/event.DomainEventHandler
> 2021-11-08T08:42:40.697Z	INFO	discovery/event_proxy.go:71	register event handler[SERVICE] service/event.ServiceEventHandler
> 2021-11-08T08:42:40.697Z	INFO	discovery/event_proxy.go:71	register event handler[INSTANCE] service/event.InstanceEventHandler
> 2021-11-08T08:42:40.697Z	INFO	discovery/event_proxy.go:71	register event handler[RULE] service/event.RuleEventHandler
> 2021-11-08T08:42:40.697Z	INFO	discovery/event_proxy.go:71	register event handler[SERVICE_TAG] service/event.TagEventHandler
> 2021-11-08T08:42:40.698Z	INFO	discovery/event_proxy.go:71	register event handler[DEPENDENCY_QUEUE] service/event.DependencyEventHandler
> 2021-11-08T08:42:40.698Z	INFO	discovery/event_proxy.go:71	register event handler[DEPENDENCY_RULE] service/event.DependencyRuleEventHandler
> 2021-11-08T08:42:40.698Z	INFO	discovery/event_proxy.go:71	register event handler[SCHEMA_SUMMARY] service/event.SchemaSummaryEventHandler
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:107	register servant controller/v3.MainService
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /version(GET)
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /health(GET)
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:107	register servant controller/v3.MicroServiceService
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /registry/v3/existence(GET)
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /registry/v3/microservices(GET)
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId(GET)
> 2021-11-08T08:42:40.699Z	INFO	rest/route.go:133	register route /registry/v3/microservices(POST)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/properties(PUT)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId(DELETE)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices(DELETE)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:107	register servant controller/v3.SchemaService
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/schemas/:schemaId(GET)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/schemas/:schemaId(PUT)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/schemas/:schemaId(DELETE)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/schemas(POST)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/schemas(GET)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:107	register servant controller/v3.DependencyService
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/dependencies(POST)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/dependencies(PUT)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:consumerId/providers(GET)
> 2021-11-08T08:42:40.700Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:providerId/consumers(GET)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:107	register servant controller/v3.TagService
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/tags(POST)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/tags/:key(PUT)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/tags(GET)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/tags/:key(DELETE)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:107	register servant controller/v3.RuleService
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/rules(POST)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/rules(GET)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/rules/:rule_id(PUT)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/rules/:rule_id(DELETE)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:107	register servant controller/v3.MicroServiceInstanceService
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/instances(GET)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances(GET)
> 2021-11-08T08:42:40.701Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances/:instanceId(GET)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances(POST)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances/:instanceId(DELETE)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances/:instanceId/properties(PUT)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances/:instanceId/status(PUT)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/instances/:instanceId/heartbeat(PUT)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/heartbeats(PUT)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:107	register servant controller/v3.WatchService
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/watcher(GET)
> 2021-11-08T08:42:40.702Z	INFO	rest/route.go:133	register route /registry/v3/microservices/:serviceId/listwatcher(GET)
> 2021-11-08T08:42:40.702Z	INFO	plugin/plugin.go:67	load 'registry' plugin named 'buildin'
> 2021-11-08T08:42:40.706Z	INFO	plugin/plugin.go:67	load 'registry' plugin named 'etcd'
> 2021-11-08T08:42:40.723Z	INFO	plugin/plugin.go:67	load 'registry' plugin named 'embeded_etcd'
> 2021-11-08T08:42:40.723Z	INFO	plugin/plugin.go:67	load 'discovery' plugin named 'aggregate'
> 2021-11-08T08:42:40.723Z	INFO	plugin/plugin.go:67	load 'discovery' plugin named 'servicecenter'
> 2021-11-08T08:42:40.723Z	INFO	plugin/plugin.go:67	load 'discovery' plugin named 'buildin'
> 2021-11-08T08:42:40.723Z	INFO	plugin/plugin.go:67	load 'discovery' plugin named 'etcd'
> 2021-11-08T08:42:40.742Z	INFO	plugin/plugin.go:67	load 'discovery' plugin named 'k8s'
> 2021-11-08T08:42:40.742Z	INFO	plugin/plugin.go:67	load 'cipher' plugin named 'buildin'
> 2021-11-08T08:42:40.742Z	INFO	plugin/plugin.go:67	load 'quota' plugin named 'unlimit'
> 2021-11-08T08:42:40.742Z	INFO	plugin/plugin.go:67	load 'auth' plugin named 'buildin'
> 2021-11-08T08:42:40.742Z	INFO	plugin/plugin.go:67	load 'uuid' plugin named 'context'
> 2021-11-08T08:42:40.743Z	INFO	plugin/plugin.go:67	load 'trace' plugin named 'buildin'
> 2021-11-08T08:42:40.743Z	INFO	plugin/plugin.go:67	load 'ssl' plugin named 'buildin'
> 2021-11-08T08:42:40.743Z	INFO	rest/route.go:107	register servant server/govern.GovernServiceControllerV3
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /registry/v3/govern/service/:serviceId(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /registry/v3/govern/relation(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /registry/v3/govern/services(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:107	register servant server/govern.GovernServiceControllerV4
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /v4/:project/govern/microservices/:serviceId(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /v4/:project/govern/relations(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /v4/:project/govern/microservices(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /v4/:project/govern/apps(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:107	register servant server/broker.BrokerController
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /pacts/provider/:providerId/consumer/:consumerId/version/:number(PUT)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /pacts/provider/:providerId/latest(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /pacts/provider/:providerId/consumer/:consumerId/version/:number(GET)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /pacts/delete(DELETE)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /pacts/provider/:providerId/consumer/:consumerId/pact-version/:sha/verification-results(POST)
> 2021-11-08T08:42:40.744Z	INFO	rest/route.go:133	register route /verification-results/consumer/:consumerId/version/:consumerVersion/latest(GET)
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 14:PARTICIPANT->/cse-pact/participant/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 15:VERSION->/cse-pact/version/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 16:PACT->/cse-pact/pact/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 17:PACT_VERSION->/cse-pact/pact-version/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 18:PACT_TAG->/cse-pact/pact-tag/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 19:VERIFICATION->/cse-pact/verification/
> 2021-11-08T08:42:40.744Z	INFO	backend/discovery.go:150	install new type 20:PACT_LATEST->/cse-pact/latest/
> 2021-11-08T08:42:40.745Z	INFO	rest/route.go:107	register servant server/admin.AdminServiceControllerV4
> 2021-11-08T08:42:40.745Z	INFO	rest/route.go:133	register route /v4/:project/admin/alarms(GET)
> 2021-11-08T08:42:40.745Z	INFO	rest/route.go:133	register route /v4/:project/admin/alarms(DELETE)
> 2021-11-08T08:42:40.745Z	INFO	rest/route.go:133	register route /v4/:project/admin/dump(GET)
> 2021-11-08T08:42:40.745Z	INFO	rest/route.go:133	register route /v4/:project/admin/clusters(GET)
> 2021-11-08T08:42:40.745Z	INFO	bootstrap/bootstrap.go:80	BootStrap ServiceComb.io Edition
> 2021-11-08T08:42:40.745Z	INFO	interceptor/interceptors.go:51	Intercept interceptor/access.Intercept
> 2021-11-08T08:42:40.745Z	INFO	interceptor/interceptors.go:51	Intercept interceptor/cors.Intercept
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/maxbody.MaxBodyHandler
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/metric.MetricsHandler
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/tracing.TracingHandler
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/auth.AuthRequest
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/context.ContextHandler
> 2021-11-08T08:42:40.745Z	INFO	chain/handler.go:41	register chain handler[_server_chain] handler/cache.CacheResponse
> 2021-11-08T08:42:40.745Z	INFO	core/config.go:128	service center is running simultaneously with 4 CPU cores
>

**Comment by libujacob** [comment]
You need mep-elaticsearch module to be running to start the api-gw and mep-server module.
If you are using the docker based deployment you can start the elastic search container using the below command.
```
docker run -itd --name mep-elasticsearch \
            --cap-drop All \
            --network=mep-net \
            -e "discovery.type=single-node" \
            swr.ap-southeast-1.myhuaweicloud.com/eg-common/elasticsearch:7.9.0
```

I would suggest you to use the offline package to bring up the edge. We use [helm](https://github.com/EdgeGallery/helm-charts/tree/master/mep) for the offline and everything is automated there. Offline package can be found [here](https://www.edgegallery.org/pc-software-download-4/) and a [guide](https://github.com/EdgeGallery/installer/blob/master/ansible_install/README-en.md) is also available to help you for the installation.

**Comment by bastien-internship** [comment]
Thank you for your answer. I will also look into your suggestion.
